spring.application.name=camplana
server.port=8080

# Ativa o perfil dev
spring.profiles.active=dev

# Configurações de Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=300MB

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

debug=true

#spring.application.name=camplana
#server.port=8080
#
## Define qual perfil está ativo:
#spring.profiles.active=dev
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=25MB
#spring.servlet.multipart.max-request-size=300MB