spring.application.name=camplana
server.port=8080

# Ativa o perfil dev
spring.profiles.active=dev

# Configurações de Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=300MB